export const COMING_SOON_DATA = 'COMING_SOON_API_URL';
export const FILMS_DATA = 'FILMS_DATA';
export const FILMS_DATA_ERROR = 'FILMS_DATA_ERROR';
export const MY_MOVIES_DATA = 'MY_MOVIES_DATA';
export const OUTSTANDING_DATA = 'OUTSTANDING_DATA';
export const POPULAR_DATA = 'POPULAR_DATA';
export const UPDATE_FLAG = 'UPDATE_FLAG';
